export default () => ({
  articles: [],
  hasNewArticles: true,
  translateCategory: {
    regional: 'Региональные новости',
    technology: 'Технологии',
    lifestyle: 'Образ жизни',
    business: 'Бизнес',
    general: 'Главное',
    programming: 'Разработка',
    software: 'Программное обеспечение',
    science: 'Наука',
    entertainment: 'Развлечения',
    world: 'В мире',
    sports: 'Спорт',
    finance: 'Финансы',
    academia: 'Научные круги',
    politics: 'Полититка',
    health: 'Здоровье',
    food: 'Еда',
    game: 'Игры',
    fashion: 'Мода',
    academic: 'Обучение',
    travel: 'Путешествия',
    culture: 'Культура',
    economy: 'Экономика',
    environment: 'Окружающая среда',
    art: 'Искусство',
    music: 'Музыка',
    CS: 'Информационные технологии',
    education: 'Образование',
    television: 'ТВ',
    commodity: 'Торговля',
    movie: 'Фильмы',
    entrepreneur: 'Предпринимательство',
    review: 'Обзор',
    auto: 'Авто',
    energy: 'Энергетика',
    celebrity: 'Звезды',
    medical: 'Медицина',
    gadgets: 'Гаджеты',
    design: 'Дизайн',
    security: 'Безопасность',
    mobile: 'Мобильные телефоны',
    estate: 'Эстетика',
    funny: 'Веселье',
  },
});
